### ISSUE TITLE
Removes SEWorldGenV2

### ISSUE THREAD

**Issue by KeepGood2016** [WesternGamer/RemoveIntroVideoPlugin#1]
Plugin works fine but when enabled it removes the SEWorldGenV2 Plugin settings from the title screen.

**Comment by WesternSpace** [comment]
It is a known issue, may attempt a fix.

**Comment by KeepGood2016** [comment]
Glad to hear, that intro video drives me insane 😂

**Comment by WesternSpace** [comment]
Fixed in [554d6f01b8861f5d9bf79a824aef3c0d2d9a48bb](https://github.com/WesternGamer/RemoveIntroVideoPlugin/commit/554d6f01b8861f5d9bf79a824aef3c0d2d9a48bb)

Should take a few minutes for the update to be available

**Comment by WesternSpace** [comment]
Works locally but not when downloaded from pluginloader.

**Comment by WesternSpace** [comment]
Will fix tomorrow.
